---
- name: set vars
  set_fact:
    docker_image: lscr.io/linuxserver/plex
    docker_container: plex
    docker_network: app-network

- name: Create config directory
  ansible.builtin.file:
    path: "{{app_plex_dir}}/config"
    state: directory
    owner: "{{app_plex_puid}}"
    group: "{{app_plex_pgid}}"
    mode: 0755

- name: Create tv directory
  ansible.builtin.file:
    path: "{{app_plex_dir}}/tv"
    state: directory
    owner: "{{app_plex_puid}}"
    group: "{{app_plex_pgid}}"
    mode: 0755

- name: Create movies directory
  ansible.builtin.file:
    path: "{{app_plex_dir}}/movies"
    state: directory
    owner: "{{app_plex_puid}}"
    group: "{{app_plex_pgid}}"
    mode: 0755

- name: Ensure image is pulled
  community.docker.docker_image:
    name: "{{ docker_image }}"
    source: pull
    force_source: yes
  register: pulled

- name: Remove container
  community.docker.docker_container:
    name: "{{ docker_container }}"
    state: absent
  when: pulled.changed

- name: Get infos on container
  community.docker.docker_container_info:
    name: "{{ docker_container }}"
  register: result

- name: Create plex container
  ansible.builtin.shell: |
    docker run -d \
    --name={{docker_container}} \
    -e PUID={{app_plex_puid}} \
    -e PGID={{app_plex_pgid}} \
    -e TZ={{app_plex_tz}} \
    -e VERSION=docker \
    -v /{{app_plex_dir}}/config:/config:Z \
    -v /{{app_plex_dir}}/tv:/tv:Z \
    -v /{{app_plex_dir}}/movies:/movies:Z \
    --network={{docker_network}} \
    --restart unless-stopped \
    {{docker_image}}
  when: 
    pulled.changed
    or
    result.exists == false
